#SPDX-License-Identifier: MIT-0
---
# tasks file for create_users
- name: Create groups
  group:
    name: "{{ item.group }}"
    state: present
  loop: "{{ users }}"
  become: yes

- name: Create users
  user:
    name: "{{ item.name }}"
    group: "{{ item.name }}"  
    shell: "{{ item.shell | default('/bin/bash') }}"
    create_home: yes
    state: present
  loop: "{{ users }}"
  become: yes

- name: Add SSH public keys
  authorized_key:
    user: "{{ item.name }}"
    key: "{{ lookup('file', item.key_file) }}"
    state: present
  loop: "{{ users }}"
  become: yes